// Code generated by manual implementation. DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/squat/terraform-provider-datacrunch/internal/sdk"
)

var (
	_ datasource.DataSource              = &ImagesDataSource{}
	_ datasource.DataSourceWithConfigure = &ImagesDataSource{}
)

func NewImagesDataSource() datasource.DataSource {
	return &ImagesDataSource{}
}

type ImagesDataSource struct {
	client *sdk.SDK
}

type ImagesDataSourceModel struct {
	Images []ImageModel `tfsdk:"images"`
}

type ImageModel struct {
	ID        types.String `tfsdk:"id"`
	ImageType types.String `tfsdk:"image_type"`
	Name      types.String `tfsdk:"name"`
	Category  types.String `tfsdk:"category"`
}

func (d *ImagesDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_images"
}

func (d *ImagesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "DataCrunch images data source",
		Attributes: map[string]schema.Attribute{
			"images": schema.ListNestedAttribute{
				MarkdownDescription: "List of available OS images",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Image ID",
							Computed:            true,
						},
						"image_type": schema.StringAttribute{
							MarkdownDescription: "Image type identifier",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "Image name",
							Computed:            true,
						},
						"category": schema.StringAttribute{
							MarkdownDescription: "Image category",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *ImagesDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T", req.ProviderData),
		)
		return
	}

	d.client = client
}

func (d *ImagesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state ImagesDataSourceModel

	// Call the API
	apiResp, err := d.client.Images.GetImages(ctx)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading images",
			fmt.Sprintf("Could not read images: %s", err.Error()),
		)
		return
	}

	if apiResp.StatusCode != 200 {
		resp.Diagnostics.AddError(
			"Error reading images",
			fmt.Sprintf("API returned status %d", apiResp.StatusCode),
		)
		return
	}

	// Parse the response body manually
	body, err := io.ReadAll(apiResp.RawResponse.Body)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading response body",
			fmt.Sprintf("Could not read response: %s", err.Error()),
		)
		return
	}

	var images []map[string]interface{}
	if err := json.Unmarshal(body, &images); err != nil {
		resp.Diagnostics.AddError(
			"Error parsing response",
			fmt.Sprintf("Could not parse JSON: %s", err.Error()),
		)
		return
	}

	// Convert to model
	state.Images = make([]ImageModel, 0, len(images))
	for _, img := range images {
		model := ImageModel{}

		if v, ok := img["id"].(string); ok {
			model.ID = types.StringValue(v)
		}
		if v, ok := img["image_type"].(string); ok {
			model.ImageType = types.StringValue(v)
		}
		if v, ok := img["name"].(string); ok {
			model.Name = types.StringValue(v)
		}
		if v, ok := img["category"].(string); ok {
			model.Category = types.StringValue(v)
		}

		state.Images = append(state.Images, model)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
