// Code generated by manual implementation. DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/squat/terraform-provider-datacrunch/internal/sdk"
)

var (
	_ datasource.DataSource              = &LocationsDataSource{}
	_ datasource.DataSourceWithConfigure = &LocationsDataSource{}
)

func NewLocationsDataSource() datasource.DataSource {
	return &LocationsDataSource{}
}

type LocationsDataSource struct {
	client *sdk.SDK
}

type LocationsDataSourceModel struct {
	Locations []LocationModel `tfsdk:"locations"`
}

type LocationModel struct {
	Code    types.String `tfsdk:"code"`
	Name    types.String `tfsdk:"name"`
	Country types.String `tfsdk:"country"`
}

func (d *LocationsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_locations"
}

func (d *LocationsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "DataCrunch datacenter locations data source",
		Attributes: map[string]schema.Attribute{
			"locations": schema.ListNestedAttribute{
				MarkdownDescription: "List of available datacenter locations",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"code": schema.StringAttribute{
							MarkdownDescription: "Location code",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "Location name",
							Computed:            true,
						},
						"country": schema.StringAttribute{
							MarkdownDescription: "Country",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *LocationsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T", req.ProviderData),
		)
		return
	}

	d.client = client
}

func (d *LocationsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state LocationsDataSourceModel

	// Call the API
	apiResp, err := d.client.Locations.GetLocations(ctx)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading locations",
			fmt.Sprintf("Could not read locations: %s", err.Error()),
		)
		return
	}

	if apiResp.StatusCode != 200 {
		resp.Diagnostics.AddError(
			"Error reading locations",
			fmt.Sprintf("API returned status %d", apiResp.StatusCode),
		)
		return
	}

	// Parse the response body manually
	body, err := io.ReadAll(apiResp.RawResponse.Body)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading response body",
			fmt.Sprintf("Could not read response: %s", err.Error()),
		)
		return
	}

	var locations []map[string]interface{}
	if err := json.Unmarshal(body, &locations); err != nil {
		resp.Diagnostics.AddError(
			"Error parsing response",
			fmt.Sprintf("Could not parse JSON: %s", err.Error()),
		)
		return
	}

	// Convert to model
	state.Locations = make([]LocationModel, 0, len(locations))
	for _, loc := range locations {
		model := LocationModel{}

		if v, ok := loc["code"].(string); ok {
			model.Code = types.StringValue(v)
		}
		if v, ok := loc["name"].(string); ok {
			model.Name = types.StringValue(v)
		}
		if v, ok := loc["country"].(string); ok {
			model.Country = types.StringValue(v)
		}

		state.Locations = append(state.Locations, model)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
