// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/squat/terraform-provider-datacrunch/internal/sdk"
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/operations"
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ provider.Provider = &DatacrunchProvider{}

type DatacrunchProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// DatacrunchProviderModel describes the provider data model.
type DatacrunchProviderModel struct {
	ServerURL    types.String `tfsdk:"server_url"`
	Bearer       types.String `tfsdk:"bearer"`
	ClientID     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
}

func (p *DatacrunchProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "datacrunch"
	resp.Version = p.version
}

func (p *DatacrunchProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: `DataCrunch Provider: Public API for datacrunch platform`,
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				MarkdownDescription: "Server URL (defaults to https://api.datacrunch.io/v1)",
				Optional:            true,
				Required:            false,
			},
			"bearer": schema.StringAttribute{
				MarkdownDescription: "OAuth2 access token (use this OR client_id/client_secret)",
				Optional:            true,
				Sensitive:           true,
			},
			"client_id": schema.StringAttribute{
				MarkdownDescription: "OAuth2 client ID (use with client_secret)",
				Optional:            true,
			},
			"client_secret": schema.StringAttribute{
				MarkdownDescription: "OAuth2 client secret (use with client_id)",
				Optional:            true,
				Sensitive:           true,
			},
		},
	}
}

func (p *DatacrunchProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data DatacrunchProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ServerURL := data.ServerURL.ValueString()

	if ServerURL == "" {
		ServerURL = "https://api.datacrunch.io/v1"
	}

	bearer := data.Bearer.ValueString()
	clientID := data.ClientID.ValueString()
	clientSecret := data.ClientSecret.ValueString()

	// If bearer token not provided, try OAuth2 with client credentials
	if bearer == "" && clientID != "" && clientSecret != "" {
		// Create temporary client for OAuth2 authentication
		tempClient := sdk.New(sdk.WithServerURL(ServerURL))

		// Get access token using client credentials
		tokenReq := &operations.GetAccessTokenRequestBody{}
		tokenReq.One = &operations.One{
			ClientID:     clientID,
			ClientSecret: clientSecret,
			GrantType:    operations.GrantTypeClientCredentials.ToPointer(),
		}

		tokenResp, err := tempClient.Authentication.GetAccessToken(ctx, tokenReq)
		if err != nil {
			resp.Diagnostics.AddError(
				"OAuth2 Authentication Failed",
				"Could not obtain access token: "+err.Error(),
			)
			return
		}

		if tokenResp.StatusCode != 200 || tokenResp.TwoHundredApplicationJSONObject == nil {
			resp.Diagnostics.AddError(
				"OAuth2 Authentication Failed",
				fmt.Sprintf("API returned status %d", tokenResp.StatusCode),
			)
			return
		}

		bearer = tokenResp.TwoHundredApplicationJSONObject.AccessToken
	}

	if bearer == "" {
		resp.Diagnostics.AddError(
			"Missing Credentials",
			"Either bearer token or client_id+client_secret must be provided",
		)
		return
	}

	security := shared.Security{
		Bearer: bearer,
	}

	opts := []sdk.SDKOption{
		sdk.WithServerURL(ServerURL),
		sdk.WithSecurity(security),
	}
	client := sdk.New(opts...)

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *DatacrunchProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewInstanceResource,
		NewSSHKeyResource,
	}
}

func (p *DatacrunchProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewInstanceTypesDataSource,
		NewImagesDataSource,
		NewLocationsDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &DatacrunchProvider{
			version: version,
		}
	}
}
