// Code generated by manual implementation. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/squat/terraform-provider-datacrunch/internal/sdk"
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/operations"
)

var (
	_ resource.Resource                = &SSHKeyResource{}
	_ resource.ResourceWithConfigure   = &SSHKeyResource{}
	_ resource.ResourceWithImportState = &SSHKeyResource{}
)

func NewSSHKeyResource() resource.Resource {
	return &SSHKeyResource{}
}

type SSHKeyResource struct {
	client *sdk.SDK
}

type SSHKeyResourceModel struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Key  types.String `tfsdk:"public_key"`
}

func (r *SSHKeyResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ssh_key"
}

func (r *SSHKeyResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "DataCrunch SSH key resource",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "SSH key ID",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "SSH key name",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"public_key": schema.StringAttribute{
				MarkdownDescription: "SSH public key content",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

func (r *SSHKeyResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *SSHKeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan SSHKeyResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Add the SSH key
	addReq := operations.AddSSHKeysRequestBody{
		Name: plan.Name.ValueString(),
		Key:  plan.Key.ValueString(),
	}

	addResp, err := r.client.SSHKeys.AddSSHKeys(ctx, addReq)
	// DataCrunch API may return text/html instead of JSON for SSH key creation
	// The SDK returns an error when content-type is not application/json, but the UUID
	// is included in the error message after "Status 201"
	var sshKeyID string
	if err != nil {
		errMsg := err.Error()
		// Check if this is a content-type error with status 201
		if strings.Contains(errMsg, "unknown content-type received") && strings.Contains(errMsg, "Status 201") {
			// The UUID is on the second line after the error description
			// Example: "unknown content-type received: text/html; charset=utf-8: Status 201\n41b4e148-..."
			lines := strings.Split(errMsg, "\n")
			if len(lines) > 1 {
				// The UUID is on the second line
				potentialID := strings.TrimSpace(lines[1])
				// Validate it looks like a UUID (contains hyphens and is reasonable length)
				if len(potentialID) >= 36 && strings.Contains(potentialID, "-") {
					sshKeyID = potentialID
					err = nil // Clear the error since we got the ID
					// Create a minimal response object for status code checking below
					addResp = &operations.AddSSHKeysResponse{StatusCode: 201}
				}
			}
		}

		if err != nil {
			resp.Diagnostics.AddError(
				"Error creating SSH key",
				fmt.Sprintf("Could not create SSH key: %s", err.Error()),
			)
			return
		}
	}

	if addResp.StatusCode != 201 && addResp.StatusCode != 200 {
		resp.Diagnostics.AddError(
			"Error creating SSH key",
			fmt.Sprintf("API returned status %d", addResp.StatusCode),
		)
		return
	}

	// If we got the ID from JSON response, use it
	if sshKeyID == "" && addResp.SSHKeyID != nil {
		sshKeyID = *addResp.SSHKeyID
	}

	if sshKeyID == "" {
		resp.Diagnostics.AddError(
			"Error creating SSH key",
			"API did not return SSH key ID",
		)
		return
	}

	// Update state from response - add returns only ID, we already have name and key from plan
	plan.ID = types.StringValue(sshKeyID)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *SSHKeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state SSHKeyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	getResp, err := r.client.SSHKeys.GetSSHKeyByID(ctx, operations.GetSSHKeyByIDRequest{
		SSHKeyID: state.ID.ValueString(),
	})

	// DataCrunch API returns array even for "get by ID", causing unmarshal error
	// The SDK's response should still have the status code and raw response
	if err != nil {
		errMsg := err.Error()
		if strings.Contains(errMsg, "cannot unmarshal array") {
			// The key exists but API returned array format
			// Since we can't parse it properly, just keep the existing state
			// This allows Delete to still be called during destroy
			return
		}
		resp.Diagnostics.AddError(
			"Error reading SSH key",
			fmt.Sprintf("Could not read SSH key %s: %s", state.ID.ValueString(), err.Error()),
		)
		return
	}

	if getResp.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}

	if getResp.SSHKey == nil {
		resp.Diagnostics.AddError(
			"Error reading SSH key",
			"API did not return SSH key",
		)
		return
	}

	// Update state from response
	state.ID = types.StringValue(getResp.SSHKey.ID)
	state.Name = types.StringValue(getResp.SSHKey.Name)
	state.Key = types.StringValue(getResp.SSHKey.Key)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *SSHKeyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// SSH keys cannot be updated - they require replacement
	resp.Diagnostics.AddWarning(
		"Update Not Supported",
		"SSH keys cannot be updated. Changes require key replacement.",
	)
}

func (r *SSHKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state SSHKeyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.SSHKeys.DeleteSSHKeyByID(ctx, operations.DeleteSSHKeyByIDRequest{
		SSHKeyID: state.ID.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError(
			"Error deleting SSH key",
			fmt.Sprintf("Could not delete SSH key %s: %s", state.ID.ValueString(), err.Error()),
		)
		return
	}
}

func (r *SSHKeyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
